aws_access_key      = "AKIAWA3G5A4WFDF4YHHV"
aws_secret_key      = "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"
aws_region          = "us-east-1"
vpc_cidr            = "10.1.0.0/16"
public_subnet1_cidr = "10.1.1.0/24"
public_subnet2_cidr = "10.1.4.0/24"
public_subnet3_cidr = "10.1.8.0/24"
vpc_name            = "terraform-aws-testing"
IGW_name            = "terraform-aws-igw"
public_subnet1_name = "Terraform_Public_Subnet1-testing"
public_subnet2_name = "Terraform_Public_Subnet2-testing"
public_subnet3_name = "Terraform_Public_Subnet3-testing"
#key_name = "LaptopKey"
host_port = "80"
#vpc_name = " "
aws_alb_protocol = "HTTP"
ec2_name         = "Terraform-Test"


